### ISSUE TITLE
Outdated App

### ISSUE THREAD

**Issue by f4dvk** [suitablebat9/Flipper-Zero-ESP8266-Deauther#1]
Hello,

I have this message : Outdated App.

Firmware version : 1.1.2

Thank you,
Stephane.

**Comment by suitablebat9** [comment]
The file should be updated. Redownload it from GitHub and let me know if you have anymore problems.

**Comment by f4dvk** [comment]
Hello,

Now it's OK.

Thank you.
Stephane.
